FROM pytorch/pytorch:2.3.1-cuda11.8-cudnn8-runtime

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Set environment variable to use CUDA
ENV CUDA_VISIBLE_DEVICES=0


CMD ["uvicorn", "embedding-service:app", "--host", "0.0.0.0", "--reload"]
